name: CI

on:
  push:
    branches: [develop, homologacao, main]
  pull_request:
    branches: [develop, homologacao, main]

env:
  APP_ENV: "test"
  DATABASE_URL: "postgresql://postgres:dbpass@127.0.0.1:5432/novosga?serverVersion=16&charset=utf8"

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: dbpass
          # base "novosga" + sufixo "_test" (dbname_suffix do when@test) = novosga_test
          POSTGRES_DB: novosga_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@2.37.1
        with:
          php-version: 8.2
          extensions: ctype, iconv, intl, pdo, pdo_pgsql, mbstring, xml, zip, curl

      - name: Install dependencies
        run: composer install

      - name: Generate certificate
        run: |
          mkdir config/jwt
          openssl genrsa -out config/jwt/private.pem 2048
          openssl rsa -in config/jwt/private.pem -pubout -out config/jwt/public.pem

      - name: PHP Code Standards
        run: vendor/bin/phpcs

      - name: PHP Code Analysis
        run: vendor/bin/phpstan

      - name: Yaml Lint
        run: |
          bin/console lint:yaml config
          bin/console lint:yaml translations

      - name: Doctrine Migrations
        run: bin/console doctrine:migrations:migrate --no-interaction

      - name: Doctrine Fixtures
        run: bin/console doctrine:fixture:load --no-interaction --purge-exclusions view_atendimentos --purge-exclusions view_atendimentos_codificados

      - name: PHP Unit Tests
        run: vendor/bin/phpunit
